<Project Sdk="Dalamud.NET.Sdk/13.1.0">
	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.0</Version>
		<Description>Fashion Report</Description>
		<PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="FashionReport.json" CopyToOutputDirectory="Always" />
		<EmbeddedResource Include="Fonts\Arcade.ttf">
			<Link>Fonts\Arcade.ttf</Link>
		</EmbeddedResource>
		<EmbeddedResource Include="Images\Icon.png" />
		<EmbeddedResource Include="Images\Cauldron.png" />
		<EmbeddedResource Include="Images\Long.png" />
		<EmbeddedResource Include="Images\Short.png" />
		<EmbeddedResource Include="Images\About.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MySqlConnector" Version="2.4.0" />
		<PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="all" />
		<PackageReference Include="Fody" Version="6.8.0" PrivateAssets="all" />
	</ItemGroup>
</Project>
